### ISSUE TITLE
Support for HAProxy's http log format

### ISSUE THREAD

**Issue by larenelg** [datalust/squiflog#24]
Support native parsing of HAProxy's http log format https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.3

An example of a Graylog extension built for it: https://marketplace.graylog.org/addons/555e70b7-dcd3-403d-bca5-6fa50bfef3cc

**Comment by jhf** [comment]
It turns out that HAProxy uses the RFC3164 syslog message format by default, but it can be changed to `rfc5424` with a simple configuration change.

Relevant excerpt from `/etc/haproxy/haproxy.conf`:
```
global
        log /dev/log format rfc5424 local0
```
Anybody trying to parse HAProxy syslog messages in Seq should start using the rfc5424 format.

**Comment by larenelg** [comment]
Thanks @jhf that's great news!
