### ISSUE TITLE
Certificate issues with recent LE certs

### ISSUE THREAD

**Issue by rjhenry** [datalust/squiflog#35]
We're using squiflog/seq-input-syslog to ingest logs as per your own documentation, but running into certificate issues when trying to connect to our Seq instance (which has a modern LE certificate signed by the R3 LE CA (in turn signed by the ISRG X1 CA).

```
Failed to send an event batch
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

The certificate *is* valid, and is being used by multiple other ingestations right now - e.g. `seq-input-gelf`.

I suspect this is to do with the recent [root CA expiry](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), but can't confirm (as we didn't have this running before then).

**Comment by KodrAus** [comment]
Hey @rjhenry :wave:

Thanks for reaching out! It's been quite a while since we've published a release of this package so I'll try pushing one through the works now and see if that picks up the new CA certificates.

**Comment by KodrAus** [comment]
We’ve just published a build using a more recent set of dependencies as `datalust/squiflog-ci:1.0.76`. We’ll promote this build to the main repository soon but if you give it a try I’ll be keen to know if it fixes things for you!

**Comment by rjhenry** [comment]
Hi @KodrAus - that has indeed fixed the issue!

**Comment by KodrAus** [comment]
Great! Thanks @rjhenry. We’ll get this build published to the production repository tomorrow.

**Comment by KodrAus** [comment]
This is all done now. The latest version `1.0.76` has up-to-date certificate configuration.
