### ISSUE TITLE
Timezone default as UTC may not always be correct

### ISSUE THREAD

**Issue by KodrAus** [datalust/squiflog#41]
Syslog supports timestamp formats that don't specify a timezone. Right now we assume these are in UTC, but they're more likely to actually be in the timezone of the host that generated them. There's no perfect solution here, but we could allow you to configure the input to use the host timezone instead of UTC.

A workaround is also to use server timestamps on the API key that forwards the events into Seq.

**Comment by nblumhardt** [comment]
We're not planning to move forward with this in the near future, since "Use server timestamps" is a reasonable workaround.
